### ISSUE TITLE
Article 42940 validation <ext-link> in table-wrap

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-jats-2-dar-jats#16]
From issue https://github.com/elifesciences/elife-jats-2-dar-jats/issues/3, I'm going to split this out to its own issue for easier tracking.

I got a hint about why the persistence tests for `42940` do not pass, when running the test directly it provides an error message like this:

```
      { _errors: [ { errors: [ { el: [Object], msg: '<ext-link> is not valid in <italic>\nSchema: (TEXT|bold|fixed-case|italic|monospace|overline|overline-start|overline-end|roman|sans-serif|sc|strike|underline|underline-start|underline-end|ruby|sub|sup)*' }, { el: [Object], msg: '<ext-link> is not valid in <italic>\nSchema: (TEXT|bold|fixed-case|italic|monospace|overline|overline-start|overline-end|roman|sans-serif|sc|strike|underline|underline-start|underline-end|ruby|sub|sup)*' }, { el: [Object], msg: '<ext-link> is not valid in <italic>\nSchema: (TEXT|bold|fixed-case|italic|monospace|overline|overline-start|overline-end|roman|sans-serif|sc|strike|underline|underline-start|underline-end|ruby|sub|sup)*' }, { el: [Object], msg: '<ext-link> is not valid in <italic>\nSchema: (TEXT|bold|fixed-case|italic|monospace|overline|overline-start|overline-end|roman|sans-serif|sc|strike|underline|underline-start|underline-end|ruby|sub|sup)*' }, { el: [Object], msg: '<ext-link> is not valid in <italic>\nSchema: (TEXT|bold|fixed-case|italic|monospace|overline|overline-start|overline-end|roman|sans-serif|sc|strike|underline|underline-start|underline-end|ruby|sub|sup)*' } ], name: 'validate-texture-article' } ] }
```

The hint being to look for `<ext-link>` tags. I found some in the table cells of the Materials and Methods table in article `42940`, for RRID links. When I removed those `<ext-link>` tags then the validation test I have returns a `pass`.

We could break tables out into a separate issue if you feel like that is a good idea @FAtherden-eLife. At a minimum, maybe you could please consider to write some XQuery to remove `<ext-link>` tags from tables?

Also to please note, although the `<italic>` and `<sup>` tags in the table do not confuse my validation script, I do not see those styles retained when viewing this Materials and Methods table in Texture. I don't know the level of support for inline styles in tables in Texture. The GUI seems to allow setting them, but the styles may not be read in from the XML file when loaded (not sure).

**Comment by fred-atherden** [comment]
@gnott when I run 42940 locally it displays/opens in Texture. But the `ext-link`s display with no formatting.

I previously raised a [bug issue with Texture](https://github.com/substance/texture/issues/1216) for this, which I have commented on, and hopefully they will re-open.

I can't find any `italic/ext-link`s in this article, although it looks like there are numerous articles with them. It seems like Texture allows for `ext-link/italic` but not `italic/ext-link.

I've accounted for that markup in my latest commit, and have [raised an issue with Texture](https://github.com/substance/texture/issues/1251) since I would regard this as a bug.

**Comment by gnott** [comment]
Hmm... I'm glad if it uncovered a potential improvement with `<ext-link><italic>` versus `<italic><ext-link>`, except from what I can see when digging around, I think the error message on this article example is a bit of a red herring.

With some poking and prodding, I may have located the issue here and regarding other tables. 

I didn't look at the actual Texture kitchen sink `manuscript.xml` very closely, and I see it has a table with inline formatting and with `<ext-link>` tags inside.

Comparing with the kitchen sink and editing the table in article `42940`, it is "valid" against the test script I am using _and_ the styles appear in Texture if... the `<td>` tags that have inline tags inside them must have an `id=""` attribute (a unique value, I suspect). I guess when the `id` is present then Texture can associate the nested tags with something, otherwise it triggers some schema validation problem and Texture in the web browser will not show the styles or links.

So, the XQuery challenge @FAtherden-eLife I think is to add a unique `id` attribute to every `<td>` tag in the XML.

As a side note, I was able to view the `42940` article in Texture, just as you were able to, even though it was reporting as invalid in the test script.

**Comment by gnott** [comment]
To be safe, and if the `id` attributes can be added by XQuery in some way, it might be safe to also add them to the `<table>` and `<tr>` tags, as it is in the texture kitchen sink XML file.

**Comment by fred-atherden** [comment]
Oh wow, excellent spot @gnott. That's really interesting. When you save in a local instance in Texture, it adds unique ids but also strips the formatting. Whereas, as you say, if the ids are present to begin with the formatting is rendered.

 I've updated the xquery to add `@id`s in, and will add that info to the Texture ticket.

**Comment by gnott** [comment]
Running the latest XQuery, it's a pass pass pass! 🍏 Thanks @FAtherden-eLife !
