### ISSUE TITLE
TexMaths may be used

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-jats-2-dar-jats#5]
Just a note that, if I understood correctly, the output XML will have TexMaths instead of MathML. Discussion and details regarding that can go into this issue.

**Comment by Melissa37** [comment]
Thanks @gnott 
We will ask Exeter to input TexMath too when we transition to Texture.
Not sure whether we can convert the archive? That would be a good thing to find out!

**Comment by fred-atherden** [comment]
The xQuery currently replaces all math with e=mc<sup>2</sup>:
https://github.com/elifesciences/elife-jats-2-dar-jats/blob/e6628b804f158049e1c9e575f5967d471cf28320/xquery/elife2dar.xq#L110-L117

I briefly looked at pre-existing transforms for MathML -> Tex, but it looked like too much work for the scope of my original work.

[Edit] - [Here's](https://github.com/transpect/mml2tex) an example of a pre-existing transform, that I had limited success with.
