### ISSUE TITLE
XQuery disp-formula conversion

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-jats-2-dar-jats#6]
In the first long run of converting eLife XML to DAR XML using the current XQuery, there were some files that reported an error. 

Some of these I attributed to being PoA XML articles, which may not be compatible with the query.

I have a way to filter out only the most recent version of each article now, and I ran a short test of converting a group of files. I saw a similar error earlier in the week with this XQuery part.

The error in my output looks like this,

```
[XUTY0006] Target is not a single node: (element p {...}, element p {...}).
failed converting ./elife-article-xml/articles/elife-22520-v2.xml
```

The line of the XQuery reported as having a problem is around line 65 https://github.com/elifesciences/elife-jats-2-dar-jats/blob/master/xquery/elife2dar.xq#L65-L67 (my line 68 in a modified XQuery I'm using), around this spot:

```
  for $x in  $copy//*:p//*:disp-formula
  return (insert node $x after $x/ancestor::*:p,
          delete node $x),
```

@FAtherden-eLife if you are able to check converting `elife-22520-v2.xml` too and see if you can reproduce the error I am seeing. If there is an error, maybe you can determine why it seems to break there on this article?

**Comment by gnott** [comment]
Additional XML files that are reporting a similar error when running the Xquery:

```
elife-00067-v1.xml
elife-01607-v1.xml
elife-02935-v2.xml
elife-03348-v2.xml
elife-04008-v1.xml
elife-04810-v1.xml
elife-04871-v2.xml
elife-04986-v1.xml
elife-05457-v1.xml
elife-05981-v2.xml
elife-06074-v2.xml
elife-06444-v2.xml
elife-07192-v1.xml
elife-08998-v3.xml
elife-09248-v2.xml
elife-10013-v1.xml
elife-10250-v2.xml
elife-10696-v1.xml
elife-15155-v1.xml
elife-16965-v4.xml
elife-22520-v2.xml
```

**Comment by fred-atherden** [comment]
Thanks @gnott - looks like these have some pretty mad markup - figure and tables placed inside `p` elements. so there are numerous ancestor `p`s for display formulas here. 

I've edited the XQuery to account for this (but let me know if you're still experiencing a similar error!). 

I'm interested how Texture handles figures and tables inside paragraphs, so have left that for now.

**Comment by gnott** [comment]
Looks good, thanks @FAtherden-eLife! I tried converting the ones listed here that did not convert the first time. Assuming no regressions (until I have the time to do a full conversion run again), there is one that didn't convert, for a new reason:

```
elife-02935-v2.xml
```

(`02935` has always been an interesting article!)

I think it might be related to issue #7 in this respect, the error I'm getting is:

```
[XUTY0006] Target is not a single node: (element contrib-group {...}, element co....
```

from this line https://github.com/elifesciences/elife-jats-2-dar-jats/blob/master/xquery/elife2dar.xq#L180

```
     insert node $x after $x/parent::*:article-meta/*:contrib-group[not(@*)]),
```

**Comment by gnott** [comment]
Looks good, thanks @FAtherden-eLife! I tried converting the ones listed here that did not convert the first time. Assuming no regressions (until I have the time to do a full conversion run again), there is one that didn't convert, for a new reason:

```
elife-02935-v2.xml
```

(`02935` has always been an interesting article!)

I think it might be related to issue #7 in this respect, the error I'm getting is:

```
[XUTY0006] Target is not a single node: (element contrib-group {...}, element co....
```

from this line https://github.com/elifesciences/elife-jats-2-dar-jats/blob/master/xquery/elife2dar.xq#L180

```
     insert node $x after $x/parent::*:article-meta/*:contrib-group[not(@*)]),
```

**Comment by gnott** [comment]
Looks good, thanks @FAtherden-eLife! I tried converting the ones listed here that did not convert the first time. Assuming no regressions (until I have the time to do a full conversion run again), there is one that didn't convert, for a new reason:

```
elife-02935-v2.xml
```

(`02935` has always been an interesting article!)

I think it might be related to issue #7 in this respect, the error I'm getting is:

```
[XUTY0006] Target is not a single node: (element contrib-group {...}, element co....
```

from this line https://github.com/elifesciences/elife-jats-2-dar-jats/blob/master/xquery/elife2dar.xq#L180

```
     insert node $x after $x/parent::*:article-meta/*:contrib-group[not(@*)]),
```

**Comment by gnott** [comment]
Looks good, thanks @FAtherden-eLife! I tried converting the ones listed here that did not convert the first time. Assuming no regressions (until I have the time to do a full conversion run again), there is one that didn't convert, for a new reason:

```
elife-02935-v2.xml
```

(`02935` has always been an interesting article!)

I think it might be related to issue #7 in this respect, the error I'm getting is:

```
[XUTY0006] Target is not a single node: (element contrib-group {...}, element co....
```

from this line https://github.com/elifesciences/elife-jats-2-dar-jats/blob/master/xquery/elife2dar.xq#L180

```
     insert node $x after $x/parent::*:article-meta/*:contrib-group[not(@*)]),
```

**Comment by gnott** [comment]
Looks good, thanks @FAtherden-eLife! I tried converting the ones listed here that did not convert the first time. Assuming no regressions (until I have the time to do a full conversion run again), there is one that didn't convert, for a new reason:

```
elife-02935-v2.xml
```

(`02935` has always been an interesting article!)

I think it might be related to issue #7 in this respect, the error I'm getting is:

```
[XUTY0006] Target is not a single node: (element contrib-group {...}, element co....
```

from this line https://github.com/elifesciences/elife-jats-2-dar-jats/blob/master/xquery/elife2dar.xq#L180

```
     insert node $x after $x/parent::*:article-meta/*:contrib-group[not(@*)]),
```

**Comment by fred-atherden** [comment]
Thanks @gnott - indeed, 02935 contains some strange markup! I'll certainly look into it in more detail next, many thanks for flagging! I've accounted for that particular XQuery issue (with `contrib-group`) in my latest commit. Let me know if any other issues!

**Comment by gnott** [comment]
I started with trying to validate `02935` again, and it was not valid. I tried to narrow down why is is not valid, and I ended up getting some better validation messages as a result. I'm going to open a new issue for article `02935` with my findings which may help you there.

**Comment by gnott** [comment]
Testing again, `elife-01607-v1.xml` is not passing validation yet due to:

```
 <disp-formula> is not valid in <list-item>
```

This is also reported in https://github.com/elifesciences/elife-jats-2-dar-jats/issues/11, so a little more is required to be confident with `<disp-formula>` tags just yet.

**Comment by fred-atherden** [comment]
Thanks @gnott, I think I've resolved this issue in my latest commit. I'll leave this for you to close in the event that's not the case.

**Comment by gnott** [comment]
Almost there I think, however the validation logic I'm using is reporting a fail. It seems to be that one `<disp-formula>` ends up inside a `<p>` tag, this one:

```
<p>
The population of the immunostained foci was denoted
<bold>A</bold>
and BODIPY stained LDs were denoted
<bold>LD</bold>
. For each colocalization experiment, a minimum of 15 snapshots was taken. Each image was first analyzed to assess the frequency of colocalization between
<bold>A</bold>
and
<bold>LD</bold>
from the experiment (1)
<bold>,</bold>
from a random situation where
<bold>A</bold>
-type particles were randomly distributed (2); both situations were then compared (3).
<disp-formula id="equ1">
<tex-math>e=mc^2</tex-math>
</disp-formula>
</p>
```

The Texture schema error is like `<disp-formula> is not valid in <p>` in this case. I'm not sure why the XQuery didn't work, it seems right to me too. Is this something you could look at again please @FAtherden-eLife ?

**Comment by fred-atherden** [comment]
Thanks @gnott, that's interesting. It's because of the following disp-formula - `//p/list/list-item/p/disp-formula` - what bizarre markup!

Accounted for in my latest commit. Once again, I'll leave this for you to close once satisfied.

**Comment by gnott** [comment]
`elife-01607-v1.xml` is also passing with the latest XQuery, thanks @FAtherden-eLife!
