### ISSUE TITLE
XQuery deleting contrib-group

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-jats-2-dar-jats#7]
Today I was able to run the XQuery again on all the most recent versions of the article XML files. The result is I found one more possible issue for when converting selected articles.

There error in this case is like this,

```
[XUTY0006] Target is not a single node: (element contrib-group {...}, element co....
```

It corresponds with this line https://github.com/elifesciences/elife-jats-2-dar-jats/blob/master/xquery/elife2dar.xq#L142 in the XQuery:

```
return (delete node $v,insert node $v after $v/preceding-sibling::*:contrib-group),
```

The list of article XML files where this is observed,

```
elife-25423-v2.xml
elife-26556-v1.xml
elife-29275-v2.xml
elife-30015-v2.xml
elife-31425-v3.xml
elife-31535-v2.xml
elife-31629-v3.xml
elife-32625-v1.xml
elife-32724-v2.xml
elife-33292-v2.xml
elife-35238-v1.xml
elife-35718-v2.xml
```

@FAtherden-eLife if you could please see if you could reproduce an error running the XQuery over one or some of these files.

**Comment by fred-atherden** [comment]
Thanks @gnott I can reproduce the error. It's because these all seem to have two editor groups - one for each, which is incorrect markup!

This should be resolved in my latest commit. Let me know if not.

**Comment by gnott** [comment]
Looking good @FAtherden-eLife thanks, all these reported above I can convert with the latest XQuery - closing!
