### ISSUE TITLE
Validation issue with <table-wrap-foot>

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-jats-2-dar-jats#9]
Continuing investigations into why so many earlier article XML files are invalid after conversion, the articles with id in the `000xx` range, I experimented with the file `elife-00065-v1.xml`.

I narrowed it down to something in the `<body>`, then tested removing the `<table-wrap>` which was also then valid. When removing only the `<table-wrap-foot>` tag it is valid.

XQuery change which works (I did not commit it) is like this:

```
 for $x in $copy//*:table-wrap-foot
  return delete node $x,
```

@FAtherden-eLife is that something you could please look at, and whether there is support for table footers in Texture, or whether the contents should be converted to different tagging rather than deleting the tag entirely?

**Comment by fred-atherden** [comment]
Thanks @gnott - Interesting, it looks like Substance previously allowed `table-wrap-foot` (although it didn't display) and have since updated it to not allow this. 

I think it would be better to simply [replace the previous query](https://github.com/elifesciences/elife-jats-2-dar-jats/blob/f72f2645cbaca763f8f285f15a9d9d7f572ff9e4/xquery/elife2dar.xq#L124-L125) which captured each `table-wrap-foot/fn` in an `fn-group` with your revised markup.

Addressed in my latest commit, and I will merge with the master branch.

**Comment by gnott** [comment]
Re-opening!  I think you may be right @FAtherden-eLife about wrapping the `<fn>` tags in an `<fn-group>` tag. In a simple test that works! 

I noticed this after spending more time looking at tables and the real Texture kitchen-sink. 

If you want to revise the XQuery to wrap the `table-wrap-foot/fn` in an `fn-group` (as you said above), that might do it.

Sorry for confusion I may have caused in my validation attempts.

**Comment by fred-atherden** [comment]
Thanks, and no problem @gnott! Texture doesn't seem to display them anyway, so no big deal. I've changed it back for now and we can revisit if/when necessary.

**Comment by gnott** [comment]
This issue wants to stay alive! Thanks @FAtherden-eLife, after another test some more specific rules will help this article reach validation: 

If there can be only one `<fn-group>` in `<table-wrap-foot>`, then it is valid, and the footnotes appear in Texture.

The desired XML for `00065` would be:

```
<table-wrap-foot>
<fn-group>
<fn>
<p>
Measurements were made using 26–27-month-old mice (n=4–5 mice/group).
</p>
</fn>
<fn id="tblfn1">
<label>*</label>
<p>4 hr fasting data.</p>
</fn>
</fn-group>
</table-wrap-foot>
```

Is it possible you could please adjust the XQuery to add only one `<fn-group>` tag?
